# utils.py
def filter_df(df, state=None, worker_type=None, sex=None, category=None):
	"""
	Applies multi-select filters to the DataFrame.
	"""
	df = df.copy()
	if state is not None and len(state) > 0:
		df = df[df['state'].isin(state)]
	if worker_type is not None and len(worker_type) > 0 and 'worker_type' in df.columns:
		df = df[df['worker_type'].isin(worker_type)]
	if sex is not None and len(sex) > 0 and 'sex' in df.columns:
		df = df[df['sex'].isin(sex)]
	if category is not None and len(category) > 0 and 'category' in df.columns:
		df = df[df['category'].isin(category)]
	return df

	
categories = {
    'Retail': [
        'Non-specialized wholesale trade',
        'Other retail sale in non-specialized stores',
        'Other retail sale not in stores, stalls or markets',
        'Other retail sale of new goods in specialized stores',
        'Other specialized wholesale',
        'Retail sale in non-specialized stores',
        'Retail sale in non-specialized stores with food, beverages or tobacco',
        'Retail sale of audio and video equipment in specialized stores',
        'Retail sale of automotive fuel in specialized stores',
        'Retail sale of beverages in specialized stores',
        'Retail sale of books, newspapers and stationary in specialized stores',
        'Retail sale of carpets, rugs, wall and floor coverings in specialized',
        'Retail sale of clothing, footwear and leather articles in specialized',
        'Retail sale of computers, peripheral units, software and',
        'Retail sale of cultural and recreation goods in specialized stores',
        'Retail sale of electrical household appliances, furniture, lighting',
        'Retail sale of food in specialized stores',
        'Retail sale of food, beverages and tobacco in specialized stores',
        'Retail sale of games and toys in specialized stores',
        'Retail sale of hardware, paints and glass in specialized stores',
        'Retail sale of information and communications equipment in specialized',
        'Retail sale of music and video recordings in specialized stores',
        'Retail sale of other goods in specialized stores',
        'Retail sale of other household equipment in specialized stores',
        'Retail sale of pharmaceutical and medical goods, cosmetic and toilet',
        'Retail sale of second-hand goods',
        'Retail sale of sporting equipment in specialized stores',
        'Retail sale of textiles in specialized stores',
        'Retail sale of tobacco products in specialized stores',
        'Retail sale via mail order houses or via Internet',
        'Retail sale via stalls and markets',
        'Retail sale via stalls and markets of food, beverages and tobacco',
        'Retail sale via stalls and markets of other goods',
        'Retail sale via stalls and markets of textiles, clothing and footwear',
        'Retail trade not in stores, stalls or markets',
        'Retail trade, except of motor vehicles and motorcycles',
        'Sale of motor vehicle parts and accessories',
        'Sale of motor vehicles',
        'Sale, maintenance and repair of motorcycles and related parts and',
        'Wholesale and retail trade and repair of motor vehicles and motorcycles',
        'Wholesale of agricultural machinery, equipment and supplies',
        'Wholesale of agricultural raw materials and live animals',
        'Wholesale of computers, computer peripheral equipment and software',
        'Wholesale of construction materials, hardware, plumbing and heating',
        'Wholesale of electronic and telecommunications equipment and parts',
        'Wholesale of food, beverages and tobacco',
        'Wholesale of household goods',
        'Wholesale of machinery, equipment and supplies',
        'Wholesale of metals and metal ores',
        'Wholesale of other household goods',
        'Wholesale of other machinery and equipment',
        'Wholesale of solid, liquid and gaseous fuels and related products',
        'Wholesale of textiles, clothing and footwear',
        'Wholesale of waste and scrap and other products n.e.c.',
        'Wholesale on a fee or contract basis',
        'Wholesale trade, except of motor vehicles and motorcycles'
    ],
    'Poultry': [
        'Raising of poultry'
    ],
    'Agriculture': [
        'Crop and animal production, hunting and related service activities',
        'Forestry and logging',
        'Growing of beverage crops',
        'Growing of cereals (except rice), leguminous crops and oil seeds',
        'Growing of citrus fruits',
        'Growing of fibre crops',
        'Growing of non-perennial crops',
        'Growing of oleaginous fruits',
        'Growing of other non-perennial crop',
        'Growing of other perennial crops',
        'Growing of other tree and bush fruits and nuts',
        'Growing of perennial crops',
        'Growing of pome fruits and stone fruits',
        'Growing of rice',
        'Growing of spices, aromatic, drug and pharmaceutical crops',
        'Growing of sugar cane',
        'Growing of tobacco',
        'Growing of tropical and subtropical fruits',
        'Growing of vegetables and melons, roots and tubers',
        'Manufacture of agricultural and forestry machinery',
        'Mixed farming',
        'Post-harvest crop activities',
        'Silviculture and other forestry activities',
        'Support activities for crop production',
        'Support activities to agriculture and post-harvest crop activities',
        'Support services to forestry'
    ],
    'Manufacturing': [
        'Animal production',
        'Data processing, hosting and related activities',
        'Data processing, hosting and related activities; web portals',
        'Distilling, rectifying and blending of spirits; ethyl alcohol production',
        'Manufacture of air and spacecraft and related machinery',
        'Manufacture of anti-sprouting products',
        'Manufacture of articles of concrete, cement and plaster',
        'Manufacture of articles of fur',
        'Manufacture of bakery products',
        'Manufacture of basic chemicals',
        'Manufacture of basic chemicals, fertilizer and nitrogen compounds, plastics',
        'Manufacture of basic iron and steel',
        'Manufacture of basic metals',
        'Manufacture of basic precious and other non-ferrous metals',
        'Manufacture of batteries and accumulators',
        'Manufacture of bearings, gears, gearing and driving elements',
        'Manufacture of beverages',
        'Manufacture of bicycles and invalid carriages',
        'Manufacture of bodies (coachwork) for motor vehicles; manufacture of',
        'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers',
        'Manufacture of builders’ carpentry and joinery',
        'Manufacture of carpets and rugs',
        'Manufacture of cement, lime and plaster',
        'Manufacture of chemicals and chemical products',
        'Manufacture of clay building materials',
        'Manufacture of cocoa, chocolate and sugar confectionery',
        'Manufacture of coke and refined petroleum products',
        'Manufacture of coke oven products',
        'Manufacture of communication equipment',
        'Manufacture of computer, electronic and optical products',
        'Manufacture of computers and peripheral equipment',
        'Manufacture of consumer electronics',
        'Manufacture of cordage, rope, twine and netting',
        'Manufacture of corrugated paper and paperboard and containers of',
        'Manufacture of cutlery, hand tools and general hardware',
        'Manufacture of dairy products',
        'Manufacture of domestic appliances',
        'Manufacture of electric lighting equipment',
        'Manufacture of electric motors, generators, transformers and electricity',
        'Manufacture of electrical equipment',
        'Manufacture of electronic components',
        'Manufacture of engines and turbines, except aircraft, vehicle and cycle',
        'Manufacture of fabricated metal products, except machinery and equipment',
        'Manufacture of fertilizers and nitrogen compounds',
        'Manufacture of fibre optic cables for data transmission or live',
        'Manufacture of fluid power equipment',
        'Manufacture of food products',
        'Manufacture of footwear',
        'Manufacture of furniture',
        'Manufacture of games and toys',
        'Manufacture of gas; distribution of gaseous fuels through mains',
        'Manufacture of general purpose machinery',
        'Manufacture of glass and glass products',
        'Manufacture of grain mill products',
        'Manufacture of grain mill products, starches and starch products',
        'Manufacture of imitation jewellery and related articles',
        'Manufacture of irradiation, electromedical and electrotherapeutic',
        'Manufacture of jewellery and related articles',
        'Manufacture of jewellery, bijouterie and related articles',
        'Manufacture of knitted and crocheted apparel',
        'Manufacture of knitted and crocheted fabrics',
        'Manufacture of leather and related products',
        'Manufacture of lifting and handling equipment',
        'Manufacture of luggage, handbags and the like, saddlery and harness',
        'Manufacture of macaroni, noodles, couscous and similar farinaceous',
        'Manufacture of machinery and equipment n.e.c.',
        'Manufacture of machinery for food, beverage and tobacco processing',
        'Manufacture of machinery for metallurgy',
        'Manufacture of machinery for mining, quarrying and construction',
        'Manufacture of machinery for textile, apparel and leather production',
        'Manufacture of made-up textile articles, except apparel',
        'Manufacture of magnetic and optical media',
        'Manufacture of malt liquors and malt',
        'Manufacture of man-made fibres',
        'Manufacture of measuring, testing, navigating and control equipment',
        'Manufacture of measuring, testing, navigating and control equipment;',
        'Manufacture of medical and dental instruments and supplies',
        'Manufacture of metal-forming machinery and machine tools',
        'Manufacture of military fighting vehicles',
        'Manufacture of motor vehicles',
        'Manufacture of motor vehicles, trailers and semi-trailers',
        'Manufacture of motorcycles',
        'Manufacture of musical instruments',
        'Manufacture of non-metallic mineral products n.e.c.',
        'Manufacture of office machinery and equipment',
        'Manufacture of optical instruments and equipment',
        'Manufacture of other articles of paper and paperboard',
        'Manufacture of other chemical products',
        'Manufacture of other chemical products n.e.c.',
        'Manufacture of other electrical equipment',
        'Manufacture of other electronic and electric wires and cables',
        'Manufacture of other fabricated metal products n.e.c.',
        'Manufacture of other fabricated metal products; metalworking service',
        'Manufacture of other food products',
        'Manufacture of other food products n.e.c.',
        'Manufacture of other general-purpose machinery',
        'Manufacture of other non-metallic mineral products',
        'Manufacture of other non-metallic mineral products n.e.c.',
        'Manufacture of other porcelain and ceramic products',
        'Manufacture of other products of wood; manufacture of articles of cork,',
        'Manufacture of other pumps, compressors, taps and valves',
        'Manufacture of other rubber products',
        'Manufacture of other special-purpose machinery',
        'Manufacture of other textiles',
        'Manufacture of other textiles n.e.c.',
        'Manufacture of other transport equipment',
        'Manufacture of other transport equipment n.e.c.',
        'Manufacture of ovens, furnaces and furnace burners',
        'Manufacture of paints, varnishes and similar coatings, printing ink and',
        'Manufacture of paper and paper products',
        'Manufacture of parts and accessories for motor vehicles',
        'Manufacture of pesticides and other agrochemical products',
        'Manufacture of pharmaceuticals, medicinal chemical and botanical',
        'Manufacture of pharmaceuticals, medicinal chemical and botanical products',
        'Manufacture of plastics and synthetic rubber in primary forms',
        'Manufacture of plastics products',
        'Manufacture of power-driven hand tools',
        'Manufacture of prepared animal feeds',
        'Manufacture of prepared meals and dishes',
        'Manufacture of products of wood, cork, straw and plaiting materials',
        'Manufacture of pulp, paper and paperboard',
        'Manufacture of railway locomotives and rolling stock',
        'Manufacture of refined petroleum products',
        'Manufacture of refractory products',
        'Manufacture of rubber and plastics products',
        'Manufacture of rubber products',
        'Manufacture of rubber tyres and tubes; retreading and rebuilding of',
        'Manufacture of soap and detergents, cleaning and polishing preparations,',
        'Manufacture of soft drinks; production of mineral waters and other',
        'Manufacture of special-purpose machinery',
        'Manufacture of sports goods',
        'Manufacture of starches and starch products',
        'Manufacture of steam generators, except central heating hot water',
        'Manufacture of structural metal products',
        'Manufacture of structural metal products, tanks, reservoirs and steam',
        'Manufacture of sugar',
        'Manufacture of tanks, reservoirs and containers of metal',
        'Manufacture of textiles',
        'Manufacture of tobacco products',
        'Manufacture of transport equipment n.e.c.',
        'Manufacture of vegetable and animal oils and fats',
        'Manufacture of veneer sheets; manufacture of plywood, laminboard,',
        'Manufacture of watches and clocks',
        'Manufacture of weapons and ammunition',
        'Manufacture of wearing apparel',
        'Manufacture of wearing apparel, except fur apparel',
        'Manufacture of wines',
        'Manufacture of wiring and wiring devices',
        'Manufacture of wiring devices',
        'Manufacture of wood and products of wood and cork, except furniture;',
        'Manufacture of wooden containers',
        'Motion picture, video and television programme post-production',
        'Motion picture, video and television programme production activities',
        'Motion picture, video and television programme production, sound recording',
        'Other manufacturing',
        'Other manufacturing n.e.c.',
        'Printing and reproduction of recorded media',
        'Processing and preserving of fish, crustaceans and molluscs',
        'Processing and preserving of fish, crustaceans and molluscs and',
        'Processing and preserving of fruit and vegetables',
        'Processing and preserving of meat',
        'Reproduction of recorded media',
        'Seed processing for propagation',
        'Support activities for animal production',
        'Tanning and dressing of leather; manufacture of luggage, handbags, saddlery'
    ],
    'Education': [
        'Cultural education',
        'Education',
        'Educational support services',
        'General secondary education',
        'Higher education',
        'Other education',
        'Other education n.e.c.',
        'Primary education',
        'Regulation of the activities of providing health care, education, cultural',
        'Secondary education',
        'Sports and recreation education',
        'Technical and vocational secondary education'
    ],
    'Healthcare': [
        'Hospital activities',
        'Human health activities',
        'Medical and dental practice activities',
        'Other human health activities',
        'Residential care activities for mental retardation, mental health and',
        'Residential care activities for mental retardation, mental health and substance',
        'Service activities incidental to air transportation',
        'Service activities incidental to land transportation',
        'Service activities incidental to water transportation'
    ]
}
def map_category(activity):
	for category, activities in categories.items():
		if activity in activities:
			return category
	return 'Other'